version: '3.3'
services:
  postgres1:
    container_name: postgres1
    image: postgres
    env_file: ./backend/.env
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
    networks:
      - bridge

  minio-service1:
    image: minio/minio
    container_name: minio-service1
    env_file: ./backend/.env
    ports:
      - 9000:9000
      - 9099:9099
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_ACCESS_KEY: lskdfhghn8975
      MINIO_SECRET_KEY: jkshdgo76
    command: server --address ":9099" --console-address ":9000" /data
    networks:
      - bridge

  createbuckets1:
    container_name: createbuckets1
    image: minio/mc
    depends_on:
      - minio-service1
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add minio http://minio-service1:9099 minioadmin minioadmin) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb minio/media;
      /usr/bin/mc policy set download minio/media;
      /usr/bin/mc mb minio/static;
      /usr/bin/mc policy set download minio/static;
      exit 0;
      "
    networks:
      - bridge

networks:
  bridge:
    driver: bridge
