version: '3.3'
services:
  postgres:
    image: postgres
    env_file: ./.env
    environment:
      POSTGRES_DB: 'blog-db'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'root'
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
  minio-service:
    image: minio/minio
    container_name: minio-service
    env_file: ./.env
    ports:
      - 9000:9000
      - 9099:9099
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ACCESS_KEY: ${MINIO_SERVER_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SERVER_SECRET_KEY}
    command: server --address ":9099" --console-address ":9000" /data
  createbuckets:
    image: minio/mc
    depends_on:
      - minio-service
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add minio http://minio-service:9099 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb minio/media;
      /usr/bin/mc policy set download minio/media;
      /usr/bin/mc mb minio/static;
      /usr/bin/mc policy set download minio/static;
      exit 0;
      "
