version: '3.9'
services:
  postgres:
    image: postgres
    env_file: ./.development.env
    environment:
      POSTGRES_DB: 'blog-db'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'root'
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
  minio-service:
    image: minio/minio
    container_name: minio-service
    env_file: ./.development.env
    ports:
      - 9000:9000
      - 9099:9099
    environment:
      MINIO_ROOT_USER: rootroot
      MINIO_ROOT_PASSWORD: rootroot
      MINIO_ACCESS_KEY: lskdfhghn8975
      MINIO_SECRET_KEY: jkshdgo76
    command: server --address ":9099" --console-address ":9000" /data
